### ISSUE TITLE
[Bug][Sonarqube] error data too long for column 'component'

### ISSUE THREAD

**Issue by aubertaa** [apache/devlake#6166]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

sonarqube extraction task fails for component too long. Ex: FIgutehrne.AnalyticsProcessing.datav3-streaming-health-monitor

Error message is:
```
subtask ExtractIssues ended unexpectedly Wraps: (2) Error 1406 (22001): Data too long for column 'component' at row 13 (500) Wraps: (3) Error 1406 (22001): Data too long for column 'component' at row 13 Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *mysql.MySQLError
```

### What do you expect to happen

Extraction should not fail.
According to sonarqube documentation, max length for component key is 400.

### How to reproduce

try to extract info from a project in sonarqube, having a project key (sonar terminology) / component (devlake terminology) length of 400.
This is the max that should work to be well integrated with sonarqube.

### Version

v0.19.0-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by abeizn** [comment]
Thanks for reporting the issue, we will follow up on it.

**Comment by abeizn** [comment]
@aubertaa The problem has been fixed and will be released in v0.19.0-beta3.

**Comment by integraci-co804** [comment]
i have the same issue in my devlake version v0.21.0@ac4f7fe, the varchar for name all table sonarqube is 255, but still error
<img width="686" alt="devlake-failure" src="https://github.com/apache/incubator-devlake/assets/170811975/f1dae3c3-ff7d-4a30-a422-e0c7b0adfe70">

**Comment by testRedlink** [comment]
Same Issue. Using v1.0.0-beta11@15c4c09

**Comment by d4x1** [comment]
> Same Issue. Using v1.0.0-beta11@15c4c09

@testRedlink 
How long is the name field in _tool_sonarqube_projects and _tool_sonarqube_accounts ?

**Comment by testRedlink** [comment]
The issue still persists. v1.0.0@44f3dea

Error running pipeline 99. Wraps: (2) Error running task 13904. | Wraps: (2) subtask convertIssueCodeBlocks ended unexpectedly | Wraps: (3) Error 1406 (22001): Data too long for column 'component' at row 10 (500) | Wraps: (4) Error 1406 (22001): Data too long for column 'component' at row 10 | Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *mysql.MySQLError Error types: (1) *hintdetail.withDetail (2) *errors.errorString

component varchar(700)

**Comment by d4x1** [comment]
@martinambrueso  Try the latest version, https://github.com/apache/incubator-devlake/releases/ , it's v1.0.1-beta3 so far.

**Comment by martinambrueso** [comment]
> @testRedlink @martinambrueso Try the latest version, https://github.com/apache/incubator-devlake/releases/ , it's v1.0.1-beta3 so far.

It's not working for me, I could see that this solution uses migrations, can i modify models to regenerate migrations?, can anyone tell me how to do this?

Thanks

**Comment by d4x1** [comment]
@martinambrueso  You can change your database schema freely: just alter columns which is too short.

**Comment by anantk24** [comment]
I am facing this issue on 1.0.2-beta1.

**Comment by klesh** [comment]
@anantk24 Could you share the specific error and how long the value was?

**Comment by anantk24** [comment]
@klesh  - Appending logs for ref.


time="2024-09-20 09:59:58" level=info msg=" [pipeline service] [pipeline #7] [task #264] [ExtractAccounts] get data from _raw_sonarqube_api_accounts where params={\"connectionId\":1,\"ProjectKey\":\"com.zesttechnologic.zekube:security\"} and got 1245"
time="2024-09-20 09:59:58" level=info msg=" [pipeline service] [pipeline #7] [task #264] [ExtractAccounts] finished records: 1(not exactly)"
time="2024-09-20 09:59:59" level=info msg=" [pipeline service] [pipeline #7] [task #264] [ExtractAccounts] finished records: 1000(not exactly)"
time="2024-09-20 10:00:00" level=info msg=" [pipeline service] [pipeline #7] [task #264] subtask ExtractAccounts finished in 1409 ms"
time="2024-09-20 10:00:00" level=info msg=" [pipeline service] [pipeline #7] [task #264] finished step: 10 / 16"
time="2024-09-20 10:00:00" level=info msg=" [pipeline service] [pipeline #7] [task #264] executing subtask convertProjects"
time="2024-09-20 10:00:00" level=info msg=" [pipeline service] [pipeline #7] [task #264] [convertProjects] finished records: 1(not exactly)"
time="2024-09-20 10:00:00" level=info msg=" [pipeline service] [pipeline #7] [task #264] subtask convertProjects finished in 4 ms"
time="2024-09-20 10:00:00" level=info msg=" [pipeline service] [pipeline #7] [task #264] finished step: 11 / 16"
time="2024-09-20 10:00:00" level=info msg=" [pipeline service] [pipeline #7] [task #264] executing subtask convertIssues"
time="2024-09-20 10:00:00" level=info msg=" [pipeline service] [pipeline #7] [task #264] [convertIssues] finished records: 1(not exactly)"
time="2024-09-20 10:00:01" level=info msg=" [pipeline service] [pipeline #7] [task #264] [convertIssues] finished records: 1000(not exactly)"
time="2024-09-20 10:00:02" level=info msg=" [pipeline service] [pipeline #7] [task #264] subtask convertIssues finished in 2017 ms"
time="2024-09-20 10:00:02" level=info msg=" [pipeline service] [pipeline #7] [task #264] finished step: 12 / 16"
time="2024-09-20 10:00:02" level=info msg=" [pipeline service] [pipeline #7] [task #264] executing subtask convertIssueCodeBlocks"
time="2024-09-20 10:00:02" level=info msg=" [pipeline service] [pipeline #7] [task #264] [convertIssueCodeBlocks] finished records: 1(not exactly)"
time="2024-09-20 10:00:05" level=info msg=" [pipeline service] [pipeline #7] [task #264] [convertIssueCodeBlocks] finished records: 858(not exactly)"
time="2024-09-20 10:00:05" level=info msg=" [pipeline service] [pipeline #7] [task #264] subtask convertIssueCodeBlocks finished in 3346 ms"
time="2024-09-20 10:00:05" level=error msg=" [pipeline service] [pipeline #7] [task #264] subtask convertIssueCodeBlocks ended unexpectedly\n\tWraps: (2) error adding result to batch (500)\n\tWraps: (3) Error 1406 (22001): Data too long for column 'component' at row 238 (500)\n\tWraps: (4) Error 1406 (22001): Data too long for column 'component' at row 238\n\tError types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *mysql.MySQLError"

**Comment by klesh** [comment]
@anantk24 Maybe connecting to the  SonarQube database and find out the length of the component field?

**Comment by anantk24** [comment]
@klesh  - Sorry I don't have access to database. By Looking at sonarqube [source code](https://github.com/SonarSource/sonarqube/blob/master/sonar-core/src/main/java/org/sonar/core/component/ComponentKeys.java#L33) I believe it is 400

**Comment by mirozani9** [comment]
Hi! We still have the same issue on version 1.0.3 beta 1

time="2025-12-23 01:51:15" level=error msg=" [pipeline service] [pipeline #162] [task #12622] subtask convertIssueCodeBlocks ended unexpectedly\n\tWraps: (2) Error 1406 (22001): Data too long for column 'component' at row 6 (500)\n\tWraps: (3) Error 1406 (22001): Data too long for column 'component' at row 6\n\tError types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *mysql.MySQLError"

DevLake can not collect data from some SonarQube projects. How to proceed with the issues?
 Thank you
